# Generated by Django 5.1.3 on 2024-11-12 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FixedAmountDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PercentageDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stores.product')),
                ('bulk_discount', models.DecimalField(decimal_places=2, default=0.15, max_digits=5)),
                ('bulk_quantity_threshold', models.IntegerField(default=10)),
            ],
            bases=('stores.product',),
        ),
        migrations.CreateModel(
            name='SeasonalProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stores.product')),
                ('seasonal_discount', models.DecimalField(decimal_places=2, default=0.1, max_digits=5)),
            ],
            bases=('stores.product',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('discount_id', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('discount_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_type', to='contenttypes.contenttype')),
                ('product_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='contenttypes.contenttype')),
            ],
        ),
    ]
